[Tue Jan 31 13:40:22.488202 2017] [:error] [pid 14864] [client 127.0.0.1:48976] mod_wsgi (pid=14864): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488333 2017] [:error] [pid 14864] [client 127.0.0.1:48976] Traceback (most recent call last):, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488376 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488430 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488450 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488478 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     response = self.handle_exception(e), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488495 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488521 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488536 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488557 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488570 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488591 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     response = self.full_dispatch_request(), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488604 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488626 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     rv = self.handle_user_exception(e), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488639 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488661 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488677 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488698 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488713 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488736 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     rv = self.dispatch_request(), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488752 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488775 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488808 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488832 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488847 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488868 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     return meth(*args, **kwargs), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488882 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/var/www/mockapi/mockapi/test/views.py", line 74, in post, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488907 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     all_data_in_array = FormActivity(jsondata).select_all_slug_data(), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488921 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/var/www/mockapi/mockapi/test/forms.py", line 63, in select_all_slug_data, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488943 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     details = self.db.select_all_slug_version(), referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.488957 2017] [:error] [pid 14864] [client 127.0.0.1:48976]   File "/var/www/mockapi/mockapi/test/models.py", line 71, in select_all_slug_version, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.489118 2017] [:error] [pid 14864] [client 127.0.0.1:48976]     self.cur.execute("SELECT  slug.title, slug_version.* FROM slug LEFT JOIN slug_version ON slug_version.slugid = slug.id");, referer: http://mockui.se/home.html
[Tue Jan 31 13:40:22.489159 2017] [:error] [pid 14864] [client 127.0.0.1:48976] OperationalError: near ".": syntax error, referer: http://mockui.se/home.html
[Tue Jan 31 14:11:39.805732 2017] [:error] [pid 16003] [client 127.0.0.1:49248] mod_wsgi (pid=16003): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.805829 2017] [:error] [pid 16003] [client 127.0.0.1:49248] Traceback (most recent call last):, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.805869 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806548 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806582 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806621 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     response = self.handle_exception(e), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806640 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806759 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806780 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806810 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806826 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806861 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     response = self.full_dispatch_request(), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806877 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806899 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     rv = self.handle_user_exception(e), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806913 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806934 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806948 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806969 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.806982 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807003 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     rv = self.dispatch_request(), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807016 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807037 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807056 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807163 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807183 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807209 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     return meth(*args, **kwargs), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807224 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/var/www/mockapi/mockapi/test/views.py", line 156, in get, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807323 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     onlyjson,slugversionid = data.select_json(), referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807343 2017] [:error] [pid 16003] [client 127.0.0.1:49248]   File "/var/www/mockapi/mockapi/test/forms.py", line 46, in select_json, referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807427 2017] [:error] [pid 16003] [client 127.0.0.1:49248]     return slugvesion[0][3], slugvesion[0][0], referer: http://mockui.se/show.html
[Tue Jan 31 14:11:39.807468 2017] [:error] [pid 16003] [client 127.0.0.1:49248] IndexError: list index out of range, referer: http://mockui.se/show.html
[Tue Jan 31 14:12:07.937155 2017] [:error] [pid 16030] [client 127.0.0.1:49256] mod_wsgi (pid=16030): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.937490 2017] [:error] [pid 16030] [client 127.0.0.1:49256] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.937623 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.938705 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.938860 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.939005 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.939125 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.939398 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.939528 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.939664 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.939787 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.939924 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.940044 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.940177 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.940320 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.940457 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.940578 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.940710 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.940829 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.940959 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.941076 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.941206 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.941319 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.941567 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.941702 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.941830 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.941941 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/var/www/mockapi/mockapi/test/views.py", line 156, in get, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.942193 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     onlyjson,slugversionid = data.select_json(), referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.942315 2017] [:error] [pid 16030] [client 127.0.0.1:49256]   File "/var/www/mockapi/mockapi/test/forms.py", line 46, in select_json, referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.942517 2017] [:error] [pid 16030] [client 127.0.0.1:49256]     return slugvesion[0][3], slugvesion[0][0], referer: http://mockui.se/update.html
[Tue Jan 31 14:12:07.942667 2017] [:error] [pid 16030] [client 127.0.0.1:49256] IndexError: list index out of range, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.853914 2017] [:error] [pid 16024] [client 127.0.0.1:49302] mod_wsgi (pid=16024): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.854003 2017] [:error] [pid 16024] [client 127.0.0.1:49302] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.854040 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.854705 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.854731 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.854765 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.854782 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.854905 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.854926 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.854955 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.854971 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.854995 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855009 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855032 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855047 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855083 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855098 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855119 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855133 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855154 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855168 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855189 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855203 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855309 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855334 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855363 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855378 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/var/www/mockapi/mockapi/test/views.py", line 156, in get, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855497 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     onlyjson,slugversionid = data.select_json(), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855519 2017] [:error] [pid 16024] [client 127.0.0.1:49302]   File "/var/www/mockapi/mockapi/test/forms.py", line 46, in select_json, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855613 2017] [:error] [pid 16024] [client 127.0.0.1:49302]     return slugvesion[0][3], slugvesion[0][0], referer: http://mockui.se/update.html
[Tue Jan 31 14:17:18.855652 2017] [:error] [pid 16024] [client 127.0.0.1:49302] IndexError: list index out of range, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935115 2017] [:error] [pid 16030] [client 127.0.0.1:49322] mod_wsgi (pid=16030): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935231 2017] [:error] [pid 16030] [client 127.0.0.1:49322] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935266 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935317 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935335 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935362 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935378 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935418 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935434 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935457 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935471 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935493 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935507 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935528 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935542 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935563 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935577 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935598 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935612 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935632 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935646 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935667 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935682 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935704 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935718 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935738 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935752 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/var/www/mockapi/mockapi/test/views.py", line 156, in get, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935776 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     onlyjson,slugversionid = data.select_json(), referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935800 2017] [:error] [pid 16030] [client 127.0.0.1:49322]   File "/var/www/mockapi/mockapi/test/forms.py", line 46, in select_json, referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935823 2017] [:error] [pid 16030] [client 127.0.0.1:49322]     return slugvesion[0][3], slugvesion[0][0], referer: http://mockui.se/update.html
[Tue Jan 31 14:17:28.935852 2017] [:error] [pid 16030] [client 127.0.0.1:49322] IndexError: list index out of range, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:57.934965 2017] [:error] [pid 19624] [client 127.0.0.1:43424] mod_wsgi (pid=19624): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:41:57.974634 2017] [:error] [pid 19624] [client 127.0.0.1:43424] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:57.974679 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:57.996631 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:57.996670 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:57.996707 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:57.996719 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009513 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009561 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009598 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009609 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009625 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009635 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009649 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009658 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009673 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009682 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009696 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009704 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009730 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009740 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009754 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.009763 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.010022 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.010038 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.010057 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.010070 2017] [:error] [pid 19624] [client 127.0.0.1:43424]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.010153 2017] [:error] [pid 19624] [client 127.0.0.1:43424]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:41:58.010185 2017] [:error] [pid 19624] [client 127.0.0.1:43424] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.589925 2017] [:error] [pid 2162] [client 127.0.0.1:43426] mod_wsgi (pid=2162): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.589993 2017] [:error] [pid 2162] [client 127.0.0.1:43426] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590017 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590634 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590652 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590674 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590684 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590778 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590792 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590808 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590817 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590831 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590839 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590863 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590873 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590886 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590895 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590908 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590916 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590929 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590937 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590950 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.590959 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.591037 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.591050 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.591066 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.591078 2017] [:error] [pid 2162] [client 127.0.0.1:43426]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.591154 2017] [:error] [pid 2162] [client 127.0.0.1:43426]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:00.591181 2017] [:error] [pid 2162] [client 127.0.0.1:43426] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.498534 2017] [:error] [pid 2156] [client 127.0.0.1:43428] mod_wsgi (pid=2156): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.498599 2017] [:error] [pid 2156] [client 127.0.0.1:43428] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.498622 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499264 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499284 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499307 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499328 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499426 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499440 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499457 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499467 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499480 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499489 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499502 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499511 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499524 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499532 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499545 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499553 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499566 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499575 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499587 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499596 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499672 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499684 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499700 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499711 2017] [:error] [pid 2156] [client 127.0.0.1:43428]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499787 2017] [:error] [pid 2156] [client 127.0.0.1:43428]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.499821 2017] [:error] [pid 2156] [client 127.0.0.1:43428] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.756638 2017] [:error] [pid 19608] [client 127.0.0.1:43430] mod_wsgi (pid=19608): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.756708 2017] [:error] [pid 19608] [client 127.0.0.1:43430] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.756735 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757552 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757581 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757609 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757621 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757726 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757741 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757759 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757769 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757783 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757792 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757806 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757815 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757828 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757837 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757850 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757859 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757871 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757880 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757904 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.757915 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.758023 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.758045 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.758072 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.758092 2017] [:error] [pid 19608] [client 127.0.0.1:43430]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.758218 2017] [:error] [pid 19608] [client 127.0.0.1:43430]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:01.758266 2017] [:error] [pid 19608] [client 127.0.0.1:43430] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.046448 2017] [:error] [pid 19610] [client 127.0.0.1:43432] mod_wsgi (pid=19610): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.046513 2017] [:error] [pid 19610] [client 127.0.0.1:43432] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.046537 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047154 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047172 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047194 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047204 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047298 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047311 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047328 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047337 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047351 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047360 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047373 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047392 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047407 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047416 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047429 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047438 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047450 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047459 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047472 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047481 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047564 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047578 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047593 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047605 2017] [:error] [pid 19610] [client 127.0.0.1:43432]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047681 2017] [:error] [pid 19610] [client 127.0.0.1:43432]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:02.047708 2017] [:error] [pid 19610] [client 127.0.0.1:43432] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.674550 2017] [:error] [pid 19609] [client 127.0.0.1:43434] mod_wsgi (pid=19609): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.674600 2017] [:error] [pid 19609] [client 127.0.0.1:43434] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.674624 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675256 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675275 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675297 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675307 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675413 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675428 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675445 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675455 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675468 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675477 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675490 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675499 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675512 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675521 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675534 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675543 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675556 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675564 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675577 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675587 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675664 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675677 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675693 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675704 2017] [:error] [pid 19609] [client 127.0.0.1:43434]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675780 2017] [:error] [pid 19609] [client 127.0.0.1:43434]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:06.675805 2017] [:error] [pid 19609] [client 127.0.0.1:43434] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.173528 2017] [:error] [pid 19611] [client 127.0.0.1:43436] mod_wsgi (pid=19611): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.173592 2017] [:error] [pid 19611] [client 127.0.0.1:43436] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.173616 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174225 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174243 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174265 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174276 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174369 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174382 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174399 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174408 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174422 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174431 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174444 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174453 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174466 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174475 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174488 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174497 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174509 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174518 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174531 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174550 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174629 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174642 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174658 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174669 2017] [:error] [pid 19611] [client 127.0.0.1:43436]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174746 2017] [:error] [pid 19611] [client 127.0.0.1:43436]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.174773 2017] [:error] [pid 19611] [client 127.0.0.1:43436] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.407830 2017] [:error] [pid 19607] [client 127.0.0.1:43438] mod_wsgi (pid=19607): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.407893 2017] [:error] [pid 19607] [client 127.0.0.1:43438] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.407917 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408628 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408652 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408676 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408686 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408784 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408798 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408816 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408825 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408839 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408848 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408861 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408870 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408894 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408904 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408917 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408926 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408939 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408948 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408960 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.408969 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.409047 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.409060 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.409075 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.409087 2017] [:error] [pid 19607] [client 127.0.0.1:43438]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.409163 2017] [:error] [pid 19607] [client 127.0.0.1:43438]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.409191 2017] [:error] [pid 19607] [client 127.0.0.1:43438] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.479759 2017] [:error] [pid 19622] [client 127.0.0.1:43440] mod_wsgi (pid=19622): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.479823 2017] [:error] [pid 19622] [client 127.0.0.1:43440] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.479847 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.480682 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.480753 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.480813 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.480833 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.480999 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481048 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481081 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481096 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481112 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481123 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481140 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481151 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481168 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481181 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481196 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481205 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481218 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481227 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481240 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481249 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481337 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481352 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481368 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481381 2017] [:error] [pid 19622] [client 127.0.0.1:43440]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481466 2017] [:error] [pid 19622] [client 127.0.0.1:43440]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.481504 2017] [:error] [pid 19622] [client 127.0.0.1:43440] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.816885 2017] [:error] [pid 19623] [client 127.0.0.1:43442] mod_wsgi (pid=19623): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.817072 2017] [:error] [pid 19623] [client 127.0.0.1:43442] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.817144 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.817891 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.817914 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.817937 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.817948 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818044 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818057 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818074 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818083 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818096 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818105 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818119 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818127 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818141 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818153 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818174 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818188 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818209 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818223 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818244 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818265 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818370 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818385 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818401 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818414 2017] [:error] [pid 19623] [client 127.0.0.1:43442]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818507 2017] [:error] [pid 19623] [client 127.0.0.1:43442]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.818549 2017] [:error] [pid 19623] [client 127.0.0.1:43442] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990089 2017] [:error] [pid 19624] [client 127.0.0.1:43444] mod_wsgi (pid=19624): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990202 2017] [:error] [pid 19624] [client 127.0.0.1:43444] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990230 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990269 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990281 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990297 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990308 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990325 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990334 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990348 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990357 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990370 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990379 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990392 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990401 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990414 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990434 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990449 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990458 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990471 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990480 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990493 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990502 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990516 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990525 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990538 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990548 2017] [:error] [pid 19624] [client 127.0.0.1:43444]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990563 2017] [:error] [pid 19624] [client 127.0.0.1:43444]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:07.990584 2017] [:error] [pid 19624] [client 127.0.0.1:43444] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344026 2017] [:error] [pid 2162] [client 127.0.0.1:43446] mod_wsgi (pid=2162): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344119 2017] [:error] [pid 2162] [client 127.0.0.1:43446] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344157 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344211 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344232 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344315 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344346 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344379 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344397 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344443 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344471 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344522 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344551 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344591 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344609 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344634 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344649 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344672 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344687 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344709 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344725 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344752 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344777 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344814 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344837 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344878 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344906 2017] [:error] [pid 2162] [client 127.0.0.1:43446]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344949 2017] [:error] [pid 2162] [client 127.0.0.1:43446]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.344990 2017] [:error] [pid 2162] [client 127.0.0.1:43446] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574585 2017] [:error] [pid 2156] [client 127.0.0.1:43448] mod_wsgi (pid=2156): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574666 2017] [:error] [pid 2156] [client 127.0.0.1:43448] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574719 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574776 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574796 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574824 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574842 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574870 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574885 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574909 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574924 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574947 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574962 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.574985 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575000 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575024 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575039 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575062 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575077 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575100 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575115 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575137 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575153 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575177 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575201 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575226 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575241 2017] [:error] [pid 2156] [client 127.0.0.1:43448]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575266 2017] [:error] [pid 2156] [client 127.0.0.1:43448]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.575299 2017] [:error] [pid 2156] [client 127.0.0.1:43448] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766491 2017] [:error] [pid 19608] [client 127.0.0.1:43450] mod_wsgi (pid=19608): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766592 2017] [:error] [pid 19608] [client 127.0.0.1:43450] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766645 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766724 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766756 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766804 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766835 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766881 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766899 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766926 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766947 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.766987 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767014 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767053 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767077 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767114 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767138 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767200 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767226 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767262 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767288 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767325 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767350 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767385 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767408 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767448 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767475 2017] [:error] [pid 19608] [client 127.0.0.1:43450]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767519 2017] [:error] [pid 19608] [client 127.0.0.1:43450]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.767573 2017] [:error] [pid 19608] [client 127.0.0.1:43450] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.949698 2017] [:error] [pid 19610] [client 127.0.0.1:43452] mod_wsgi (pid=19610): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.949819 2017] [:error] [pid 19610] [client 127.0.0.1:43452] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.949877 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.949960 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.949996 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950048 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950073 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950104 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950121 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950146 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950186 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950213 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950229 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950253 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950269 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950293 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950308 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950331 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950347 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950369 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950385 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950408 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950424 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950449 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950464 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950488 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950503 2017] [:error] [pid 19610] [client 127.0.0.1:43452]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950530 2017] [:error] [pid 19610] [client 127.0.0.1:43452]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:08.950566 2017] [:error] [pid 19610] [client 127.0.0.1:43452] KeyError: 'versionID', referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.578884 2017] [:error] [pid 19623] [client 127.0.0.1:43462] mod_wsgi (pid=19623): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'., referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.578929 2017] [:error] [pid 19623] [client 127.0.0.1:43462] Traceback (most recent call last):, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.578950 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.578993 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     return self.wsgi_app(environ, start_response), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579005 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579021 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     response = self.handle_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579032 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579053 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579063 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579077 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579087 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579099 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     response = self.full_dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579108 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579121 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     rv = self.handle_user_exception(e), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579130 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579143 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     return cors_after_request(app.make_response(f(*args, **kwargs))), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579152 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579165 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     reraise(exc_type, exc_value, tb), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579173 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579187 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     rv = self.dispatch_request(), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579200 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579216 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579226 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579240 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     return self.dispatch_request(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579248 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579270 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     return meth(*args, **kwargs), referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579280 2017] [:error] [pid 19623] [client 127.0.0.1:43462]   File "/var/www/mockapi/mockapi/test/views.py", line 128, in post, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579295 2017] [:error] [pid 19623] [client 127.0.0.1:43462]     'versionid' : modified_json['versionID'],, referer: http://mockui.se/update.html
[Thu Feb 02 00:42:39.579315 2017] [:error] [pid 19623] [client 127.0.0.1:43462] KeyError: 'versionID', referer: http://mockui.se/update.html
[Sun Feb 05 18:16:30.579999 2017] [:error] [pid 1681] [client 127.0.0.1:34516] mod_wsgi (pid=1681): Exception occurred processing WSGI script '/var/www/mockapi/mockapi.wsgi'.
[Sun Feb 05 18:16:30.607581 2017] [:error] [pid 1681] [client 127.0.0.1:34516] Traceback (most recent call last):
[Sun Feb 05 18:16:30.607629 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
[Sun Feb 05 18:16:30.630894 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     return self.wsgi_app(environ, start_response)
[Sun Feb 05 18:16:30.630930 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
[Sun Feb 05 18:16:30.630965 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     response = self.handle_exception(e)
[Sun Feb 05 18:16:30.630975 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
[Sun Feb 05 18:16:30.643771 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Sun Feb 05 18:16:30.643807 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
[Sun Feb 05 18:16:30.643842 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     reraise(exc_type, exc_value, tb)
[Sun Feb 05 18:16:30.643852 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
[Sun Feb 05 18:16:30.643866 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     response = self.full_dispatch_request()
[Sun Feb 05 18:16:30.643874 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
[Sun Feb 05 18:16:30.643886 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     rv = self.handle_user_exception(e)
[Sun Feb 05 18:16:30.643897 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
[Sun Feb 05 18:16:30.643914 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Sun Feb 05 18:16:30.643922 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
[Sun Feb 05 18:16:30.643933 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     reraise(exc_type, exc_value, tb)
[Sun Feb 05 18:16:30.643940 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
[Sun Feb 05 18:16:30.643951 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     rv = self.dispatch_request()
[Sun Feb 05 18:16:30.643958 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
[Sun Feb 05 18:16:30.643969 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     return self.view_functions[rule.endpoint](**req.view_args)
[Sun Feb 05 18:16:30.643977 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
[Sun Feb 05 18:16:30.644231 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     return self.dispatch_request(*args, **kwargs)
[Sun Feb 05 18:16:30.644246 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request
[Sun Feb 05 18:16:30.644262 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     return meth(*args, **kwargs)
[Sun Feb 05 18:16:30.644270 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/var/www/mockapi/mockapi/test/views.py", line 156, in get
[Sun Feb 05 18:16:30.644352 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     onlyjson,slugversionid = data.select_json()
[Sun Feb 05 18:16:30.644364 2017] [:error] [pid 1681] [client 127.0.0.1:34516]   File "/var/www/mockapi/mockapi/test/forms.py", line 43, in select_json
[Sun Feb 05 18:16:30.644421 2017] [:error] [pid 1681] [client 127.0.0.1:34516]     slugvesion = self.db.select_from_slug_version(slug[0][0], self.data['version'])
[Sun Feb 05 18:16:30.644449 2017] [:error] [pid 1681] [client 127.0.0.1:34516] IndexError: list index out of range
